import time
from pygame import mixer
print('正在播放第一首歌')
mixer.init()
a = mixer.Sound("黑人抬棺.mp3")
a.play()
time.sleep(199)
print("正在播放第二首歌")
mixer.init()
b = mixer.Sound("Selena Gomez、Marshmello-Wolves (Kuur X Jason Bouse Remix).mp3")
b.play()
time.sleep(217)
print("正在播放第三首歌")
mixer.init()
c = mixer.Sound("祺明 - 辞九门回忆（DJ咚鼓版）.mp3")
c.play()
time.sleep(217)
print('正在播放第四首歌')
mixer.init()
d = mixer.Sound("Voice.mp3")
d.play()
time.sleep(301)
print('正在播放第五首歌')
mixer.init()
e = mixer.Sound("Move up.mp3")
e.play()
time.sleep(185)
print('正在播放第六首歌')
mixer.init()
f = mixer.Sound("Different Heaven - Nekozilla.mp3")
f.play()
time.sleep(168)
